[package]
name = "wasm-token-example"
version = "0.1.0"
authors = ["Alexey Frolov <frol.rage@gmail.com>"]

[dependencies]
pwasm-std = "0.2"
pwasm-abi = { git = "https://github.com/paritytech/pwasm-abi" }
pwasm-abi-derive = { git = "https://github.com/paritytech/pwasm-abi", path = "derive" }
tiny-keccak = "1.3"


[dev-dependencies]
pwasm-test = { git = "https://github.com/paritytech/pwasm-test" }

[[bin]]
name = "token"
path = "src/token.rs"

[profile.release]
panic = "abort"
lto = true

[features]
std = ["pwasm-std/std"]
