[package]
name = "wasm-token-example"
version = "0.1.0"
authors = ["Alexey Frolov <frol.rage@gmail.com>"]

[dependencies]
pwasm-std = { git = "https://github.com/paritytech/pwasm-std" }
pwasm-abi = { git = "https://github.com/paritytech/pwasm-abi" }
pwasm-abi-derive = { git = "https://github.com/paritytech/pwasm-abi", path = "derive" }

[dev-dependencies]
pwasm-test = { git = "https://github.com/paritytech/pwasm-test" }

[[bin]]
name = "token"
path = "src/token.rs"


[profile.release]
panic = "abort"


[features]
std = ["pwasm-std/std"]
