[package]
name = "pwasm-token-contract"
version = "0.1.0"
authors = ["Alexey Frolov <frol.rage@gmail.com>"]

[dependencies]
pwasm-std = "0.3"
pwasm-ethereum = { git = "https://github.com/nikvolf/pwasm-ethereum" }
pwasm-abi = { git = "https://github.com/paritytech/pwasm-abi" }
pwasm-abi-derive = { git = "https://github.com/paritytech/pwasm-abi" }
tiny-keccak = "1.3"

[dependencies.bigint]
version = "4"
default-features = false

[dependencies.parity-hash]
version = "1"
default-features = false

[dev-dependencies]
pwasm-test = { git = "https://github.com/paritytech/pwasm-test" }

[features]
std = ["pwasm-std/std", "pwasm-ethereum/std"]

[replace]
"pwasm-std:0.3.2" = { git = "https://github.com/paritytech/pwasm-std", branch="rlibc" }
"pwasm-std:0.3.0" = { git = "https://github.com/paritytech/pwasm-std", branch="rlibc" }